export const all_listing = [
  {
    id: 10006546,
    host_id: 51399391,
    listing_url: 'https://www.airbnb.com/rooms/10006546',
    name: 'Ribeira Charming Duplex',
    summary:
      'Fantastic duplex apartment with three bedrooms, located in the historic area of Porto, Ribeira (Cube)...',
    interaction: 'Cot - 10 € / night Dog - € 7,5 / night',
    house_rules: 'Make the house your home...',
    property_type: 'House',
    room_type: 'Entire home/apt',
    bed_type: 'Real Bed',
    minimum_nights: 2,
    maximum_nights: 30,
    cancellation_policy: 'moderate',
    last_scraped: '1550293200000',
    calendar_last_scraped: '1550293200000',
    accommodates: 8,
    bedrooms: 3,
    beds: 5,
    number_of_reviews: 51,
    bathrooms: 1.0,
    amenities: [
      'TV',
      'Cable TV',
      'Wifi',
      'Kitchen',
      'Paid parking off premises',
      'Smoking allowed',
      'Pets allowed',
      'Buzzer/wireless intercom',
      'Heating',
      'Family/kid friendly',
      'Washer',
      'Coffee maker',
      'Refrigerator',
      'Dishwasher',
      'Dishes and silverware',
      'Cooking basics',
      'Oven',
      'Stove',
      'Cleaning before checkout',
      'Waterfront',
    ],
    price: 80.0,
    security_deposit: 200.0,
    cleaning_fee: 35.0,

    extra_people: 15.0,
    guests_included: 6,
    images: [
      {
        thumbnail_url: '',
        medium_url: '',
        picture_url:
          'https://a0.muscache.com/im/pictures/e83e702f-ef49-40fb-8fa0-6512d7e26e9b.jpg?aki_policy=large',
        xl_picture_url: '',
      },
    ],
    address: {
      street: 'Porto, Porto, Portugal',
      suburb: '',
      government_area: 'Cedofeita, Ildefonso, Sé, Miragaia, Nicolau, Vitória',
      market: 'Porto',
      country: 'Portugal',
      country_code: 'PT',
      location: {
        type: 'Point',
        coordinates: {
          x: '-8.61308',
          y: '41.1413',
        },
        is_location_exact: false,
      },
    },
    availability: {
      availability_30: 28,
      availability_60: 47,
      availability_90: 74,
      availability_365: 239,
    },
    review_id: 27,
  },
]

export const hosts = [
  {
    host_id: 51399391,
    host_url: 'https://www.airbnb.com/users/show/51399391',
    host_name: 'Ana&Gonçalo',
    host_location: 'Porto, Porto District, Portugal',
    hosting_experience_years: 3,
    host_about:
      'Gostamos de passear, de viajar, de conhecer pessoas e locais novos, gostamos de desporto e animais! Vivemos na cidade mais linda do mundo!!!',
    host_response_time: 'within an hour',
    host_thumbnail_url:
      'https://a0.muscache.com/im/pictures/fab79f25-2e10-4f0f-9711-663cb69dc7d8.jpg?aki_policy=profile_small',
    host_picture_url:
      'https://a0.muscache.com/im/pictures/fab79f25-2e10-4f0f-9711-663cb69dc7d8.jpg?aki_policy=profile_x_medium',
    host_school: 'Instituto de Biociencias USP',
    host_fun_fact: '?',
    host_breakfast: 'Fruits juice, milk,eggs vegan options',
    host_work_info:
      'Roberta Yoga Massage, UlaBiná, Rede TVT, João do Grão, Body Therapist',
    host_fav_song: 'Favorite song in high school: Ovelha negra, Rita Lee',
    host_languages: 'Portuguese, English, Spanish',
    host_home_unique: 'The nature that surrounds it. You. Namaste!',
    host_birth_info: 'Born in the 60s',
    host_obssession: 'Yoga, meditation, massage, nature, animals, vegan food',
    host_response_rate: 100,
    host_is_superhost: false,
    host_has_profile_pic: true,
    host_identity_verified: true,
    host_listings_count: 3,
    host_total_listings_count: 3,
    host_interests: ['ARTS', 'MUSIC', 'YOGA', 'NATURE', 'ANIMALS', 'VEGAN'],
    host_verifications: {
      identity_verified: true,
      email_verified: true,
      phone_verified: true,
    },
  },
]

const review = [
  {
    review_id: 27,
    review_scores: {
      review_scores_accuracy: 4,
      review_scores_cleanliness: 4,
      review_scores_checkin: 4,
      review_scores_communication: 4,
      review_scores_location: 4,
      review_scores_value: 4,
      review_scores_rating: 4,
    },
    reviews: [
      {
        id: 362865132,
        date: '1545886800000',
        listing_id: 10006546,
        reviewer_id: 208880077,
        reviewer_name: 'Thomas',
        comments: 'Very helpful hosts. Cooked traditional...',
      },
      {
        id: 364728730,
        date: '1546232400000',
        listing_id: 10006546,
        reviewer_id: 91827533,
        reviewer_name: 'Mr',
        comments: 'Ana & Goncalo were great on communication...',
      },
      {
        id: 403055315,
        date: '1547960400000',
        listing_id: 10006546,
        reviewer_id: 15138940,
        reviewer_name: 'Milo',
        comments: 'The house was extremely well located...',
      },
    ],
  },
]
